include:
  - project: widas/software-quality/gitlab-template-projects/widas-customer-ci-templates
    file: java/java-mvn-lib.yml

stages:
  - prepare
  - test
  - build
  - release
  - badges
  - deploy

get_prereqiusites:
  before_script:
    - rm -rf common-templates

test:
  stage: test
  image: maven:3-openjdk-17
  script:
      - mvn test
      - awk -F"," '{ covered += $5; total += $4 + $5 } END { print covered, "/", total, "instructions covered"; printf "%s %0.2f", "code coverage:", 100*covered/total; print "%" }' target/site/jacoco/jacoco.csv
  coverage: '/code coverage: ([\d\.]+)%/'
  artifacts:
    expire_in: 1 hrs
    paths:
      - target/*

code_quality_json:
  image: docker:git
  stage: test
  allow_failure: true
  variables:
    CODE_QUALITY_IMAGE: "codeclimate/codeclimate:latest"
    QUALITY_BASE_REPO: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.widas.de/widas/codequality.git
  script:
    - docker pull "$CODE_QUALITY_IMAGE"
    - git clone ${QUALITY_BASE_REPO}
    - cp codequality/conf/codeclimate/rules/java/.codeclimate.yml .
    - rm -rf codequality
    - docker run 
       --env SOURCE_CODE="$PWD"
       --env CODECLIMATE_CODE="$PWD"
       --volume "$PWD":/code 
       --volume /var/run/docker.sock:/var/run/docker.sock 
       --volume /tmp/cc:/tmp/cc 
       "$CODE_QUALITY_IMAGE" analyze -f json > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]

build:
  extends: .build