include:
  - project: 'widas/codequality'
    ref: master
    file: 'ci_templates/java.gitlab-ci.yml'

stages:
  - test
  - badges
  - deploy

maven_build:
  extends: build
  image: maven:3-openjdk-11