include:
  - project: widas/software-quality/gitlab-template-projects/widas-customer-ci-templates
    file: java/java-mvn-lib.yml

stages:
  - prepare
  - test
  - build
  - release
  - badges
  - deploy

test:
  extends: .test

build:
  extends: .build