include:
  - project: widas/software-quality/gitlab-template-projects/widas-customer-ci-templates
    ref: master
    file: java/java-mvn-lib.yml

stages:
  - test
  - build
  - release
  - badges
  - deploy

test:
  extends: .test

maven_build:
  extends: build
  image: maven:3-openjdk-11